file_path: './data/resale_transactions_categorised.csv'
target_column: price_category
val_test_size: 0.2
val_size: 0.5
param_grid:
  ridge_tuned:
    classifier__alpha: [0.1, 1.0, 10.0]
  logistic_regression:
    C: [0.001, 0.01, 0.1, 1, 10, 100]
    penalty: ['l2']
    solver: ['lbfgs']
    MAX_ITER : [1000]
    RANDOM_STATE : [42]
    Cross Validation: GridSearchCV 
    cv: 5
    scoring: ['roc_auc'] 
    n_jobs: -1 
    verbose: 1
  knn:
    n_neighbors: [3, 5, 7, 9, 11, 13, 15]
    weights: ['uniform', 'distance']
    Cross Validation: RandomizedSearchCV 
    n_iter: 4 
    cv: 2 
    scoring: 'roc_auc'
    random_state: RANDOM_STATE 
    n_jobs: -1 
    verbose: 1
  decision_tree:
    max_depth: [3, 5, 7, 10, None]
    min_samples_split: [2, 5, 10, 15, 20]
    min_samples_leaf:  [1, 2, 4, 8, 10]
    Cross Validation: GridSearchCV 
    cv: 5 
    scoring: ['roc_auc'] 
    n_jobs: -1 
    verbose: 1 
scoring: ROC AUC score 
numerical_features:
  - floor_area_sqm
  - remaining_lease_months
  - lease_commence_date
  - year
nominal_features:
  - month
  - town_name
  - flatm_name
  - storey_range
ordinal_features:
  - flat_type
passthrough_features: []

flat_type_categories:
  - "1 ROOM"
  - "2 ROOM"
  - "3 ROOM"
  - "4 ROOM"
  - "5 ROOM"
  - "MULTI-GENERATION"
  - "EXECUTIVE"

target_column: price_category
val_test_size: 0.2
val_size: 0.5
param_grid:
  ridge_tuned:
    classifier__alpha: [0.1, 1.0, 10.0]
cv: 5
scoring: f1  # Ensure this line is present